INSERT INTO <SCH><THIP>PARAM_PSN (ID_PROGRESSIVO, ID_FUNZIONE, ID_PARAMETRO, ID_AZIENDA, DESCRIZIONE, DESCR_RIDOTTA, R_RIFER_ATTRIB, VALORE_PARAM, STATO, R_UTENTE_CRZ, R_UTENTE_AGG, NOTA, AREA, NUMERO_FIX) VALUES (<NUM><PARAM_PSN>, 'YCopiaPallet', 'SerieScatola', null, 'Serie scatola in funzione copia pal', 'Serie scatola i', 'IdSerieNumeratori', 'SA', 'V', <USER>, <USER> , null, '-' , null);
INSERT INTO <SCH><THIP>PARAM_PSN_L (ID_PROGRESSIVO, ID_LINGUA, DESCRIZIONE, DESCR_RIDOTTA) VALUES (<LAST_NUM><PARAM_PSN>,'it', 'Serie scatola in funzione copia pal', 'Serie scatola i');


